version: "3"

services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 server.php
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.28-oracle
    #image: mysql:8.0
    #platform: linux/x86_64
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 33062:3306

  adminer:
    image: adminer:4.7.5
    ports:
      - 5001:8080
    depends_on:
      - mysql